server:
  port: 12000
  servlet:
    context-path: /gateway

spring:
  application:
    name: gateway

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos

    gateway:
      routes:
        - id: stock_route # 当前路由的标识, 要求唯一

          # 请求要转发到的地址
          # 1.单独使用 gateway,
          # uri: http://localhost:10001
          # 2.使用nacos, lb 指的是从 nacos 中按照名称获取微服务,并遵循负载均衡策略
          uri: lb://stock-nacos

          order: 1 # 路由的优先级, 数字越小优先级越高
          predicates: # 断言, 就是路由转发要满足的条件
            - Path=/gateway/stock/** # 当请求路径满足Path指定的规则时才进行路由转发
          filters: # 过滤器, 请求在传递过程中可以通过过滤器对其进行一定的修改
            - StripPrefix=1 # 转发之前去掉一层路径

        - id: product_route # 当前路由的标识, 要求唯一

          # 请求要转发到的地址
          # 1.单独使用 gateway,
          # uri: http://localhost:10001
          # 2.使用nacos, lb 指的是从 nacos 中按照名称获取微服务,并遵循负载均衡策略
          uri: lb://product-service

          order: 1 # 路由的优先级, 数字越小优先级越高
          predicates: # 断言, 就是路由转发要满足的条件
            - Path=/gateway/prod/** # 当请求路径满足Path指定的规则时才进行路由转发
          filters: # 过滤器, 请求在传递过程中可以通过过滤器对其进行一定的修改
            - StripPrefix=1 # 转发之前去掉一层路径