server:
  port: 8080

spring:
  application:
    # 此名字会向 Eureka 注册
    name: spb-server-eureka
eureka:
  client:
    service-url:
      # 具体哪个地址提供了 Eureka 服务
      defaultZone:
        http://localhost:8761/eureka/
grpc:
  server:
    # 采用一个未占用的随机端口号来提供 gRPC 服务
    port: 0

