server:
  port: 8081

spring:
  application:
    # 会把这个名字注册到 Eureka 注册中心
    name: spb-client-eureka
  eureka:
    client:
    service-url:
      # 具体哪个地址提供了 Eureka 服务
      defaultZone:
        http://localhost:8761/eureka/
grpc:
  client:
    # 自定义名称,且需服务端的 application 名(即注册到 eureka 的服务名)相同,不需要再显式的写明地址端口号
    spb-server-eureka:
      # 声明传输格式
      negotiation-type: plaintext
